In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%cd drive/MyDrive/Projeto\ disciplina\ PCS5787
!pwd

/content/drive/MyDrive/Projeto disciplina PCS5787
/content/drive/MyDrive/Projeto disciplina PCS5787

In [ ]:
import pandas as pd
pd.set_option('display.float_format', lambda x: '%.2f' % x)

In [ ]:
df_iptu = pd.read_csv('IPTU_2019_2024.csv')

display(df_iptu.head(20))
display(df_iptu.info())

,NUMERO DO CONTRIBUINTE,ANO DO EXERCICIO,NOME DE LOGRADOURO DO IMOVEL,NUMERO DO IMOVEL,AREA DO TERRENO,AREA CONSTRUIDA,AREA OCUPADA,VALOR DO M2 DO TERRENO,VALOR DO M2 DE CONSTRUCAO,TIPO DE USO DO IMOVEL,TIPO DE PADRAO DA CONSTRUCAO
0,100300014,2019,R S CAETANO,13.00,136.00,135.00,108.00,2241,1668,Loja,Comercial horizontal - padrão B
1,100300022,2019,R S CAETANO,19.00,90.00,67.00,67.00,2241,1668,Loja,Comercial horizontal - padrão B
2,100300030,2019,R S CAETANO,27.00,105.00,140.00,84.00,2241,1668,Loja,Comercial horizontal - padrão B
3,100300049,2019,R S CAETANO,33.00,108.00,103.00,86.00,2241,1668,Loja,Comercial horizontal - padrão B
4,100300057,2019,R S CAETANO,39.00,120.00,98.00,96.00,2241,1668,Loja,Comercial horizontal - padrão B
5,100300065,2019,R S CAETANO,49.00,310.00,1804.00,285.00,2241,2139,"Prédio de apartamento, não em condomínio, de u...",Residencial vertical - padrão C
6,100300073,2019,R S CAETANO,57.00,257.00,802.00,257.00,2241,2139,Loja e residência (predominância comercial),Comercial vertical - padrão B
7,100300081,2019,R S CAETANO,69.00,167.00,248.00,133.00,2241,1668,Loja,Comercial horizontal - padrão B
8,100300091,2019,R S CAETANO,75.00,112.00,150.00,80.00,2241,1668,Loja,Comercial horizontal - padrão B
9,100300103,2019,R S CAETANO,83.00,303.00,660.00,297.00,2241,2584,Loja,Comercial vertical - padrão C
10,100300111,2019,R S CAETANO,89.00,285.00,505.00,206.00,2241,2139,"Outras edificações de uso comercial, com utili...",Comercial vertical - padrão B
11,100300121,2019,R S CAETANO,99.00,256.00,1082.00,256.00,2241,2139,"Outras edificações de uso comercial, com utili...",Comercial vertical - padrão B
12,100300138,2019,R S CAETANO,113.00,120.00,166.00,96.00,2241,1668,Loja,Comercial horizontal - padrão B
13,100300154,2019,R DUTRA RODRIGUES,43.00,162.00,740.00,156.00,1251,2139,Loja e residência (predominância comercial),Comercial vertical - padrão B
14,100300170,2019,R DUTRA RODRIGUES,59.00,168.00,336.00,168.00,1251,1668,"Outras edificações de uso comercial, com utili...",Comercial horizontal - padrão B
15,100300227,2019,R DUTRA RODRIGUES,85.00,156.00,456.00,150.00,1251,2139,Loja e residência (predominância comercial),Comercial vertical - padrão B
16,100300235,2019,R DUTRA RODRIGUES,89.00,150.00,200.00,100.00,1251,1755,Residência e outro uso (predominância residenc...,Residencial horizontal - padrão C
17,100300243,2019,R DUTRA RODRIGUES,95.00,156.00,200.00,100.00,1251,1668,Loja e residência (predominância comercial),Comercial horizontal - padrão B
18,100300261,2019,R DUTRA RODRIGUES,147.00,171.00,630.00,171.00,1251,2139,Loja,Comercial vertical - padrão B
19,100300278,2019,R DUTRA RODRIGUES,149.00,150.00,150.00,120.00,1251,1668,Loja e residência (predominância comercial),Comercial horizontal - padrão B

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21317317 entries, 0 to 21317316
Data columns (total 11 columns):
 #   Column                        Dtype
---  ------                        -----
 0   NUMERO DO CONTRIBUINTE        int64
 1   ANO DO EXERCICIO              int64
 2   NOME DE LOGRADOURO DO IMOVEL  object
 3   NUMERO DO IMOVEL              float64
 4   AREA DO TERRENO               float64
 5   AREA CONSTRUIDA               float64
 6   AREA OCUPADA                  float64
 7   VALOR DO M2 DO TERRENO        int64
 8   VALOR DO M2 DE CONSTRUCAO     int64
 9   TIPO DE USO DO IMOVEL         object
 10  TIPO DE PADRAO DA CONSTRUCAO  object
dtypes: float64(4), int64(4), object(3)
memory usage: 1.7+ GB

None

In [ ]:
df_iptu["NUMERO DO CONTRIBUINTE"] = df_iptu["NUMERO DO CONTRIBUINTE"].astype("object")
df_iptu["ANO DO EXERCICIO"] = df_iptu["ANO DO EXERCICIO"].astype("object")

## Analyze missing data

In [ ]:
missing_values = df_iptu.isnull().sum()
display(missing_values)

NUMERO DO CONTRIBUINTE               0
ANO DO EXERCICIO                     0
NOME DE LOGRADOURO DO IMOVEL         0
NUMERO DO IMOVEL                512450
AREA DO TERRENO                      0
AREA CONSTRUIDA                      0
AREA OCUPADA                         0
VALOR DO M2 DO TERRENO               0
VALOR DO M2 DE CONSTRUCAO            0
TIPO DE USO DO IMOVEL                0
TIPO DE PADRAO DA CONSTRUCAO         0
dtype: int64

## Generate descriptive statistics

In [ ]:

numerical_columns = df_iptu.select_dtypes(include=['int64', 'float64'])
descriptive_stats = numerical_columns.describe()
display(descriptive_stats)

,NUMERO DO IMOVEL,AREA DO TERRENO,AREA CONSTRUIDA,AREA OCUPADA,VALOR DO M2 DO TERRENO,VALOR DO M2 DE CONSTRUCAO
count,20804867.00,21317317.00,21317317.00,21317317.00,21317317.00,21317317.00
mean,581.87,3986.78,154.29,1304.12,2462.21,1846.71
std,1124.40,16923.68,1057.46,3451.62,3144.23,819.97
min,0.00,1.00,0.00,0.00,45.00,0.00
25%,102.00,185.00,63.00,90.00,682.00,1322.00
50%,262.00,711.00,100.00,324.00,1331.00,1774.00
75%,619.00,2481.00,153.00,1234.00,2870.00,2291.00
max,99541.00,4307493.00,950328.00,464200.00,32871.00,4249.00

## Analyze categorical data

In [ ]:
categorical_columns = df_iptu.select_dtypes(include='object').columns.tolist()

categorical_columns.remove('NUMERO DO CONTRIBUINTE')
categorical_columns.remove('ANO DO EXERCICIO')

for col in categorical_columns:
    print(f"\nValue counts for column: {col}")
    # Display top 20 categories for columns with many unique values
    if df_iptu[col].nunique() > 20:
        display(df_iptu[col].value_counts().head(20))
    else:
        display(df_iptu[col].value_counts())

Value counts for column: NOME DE LOGRADOURO DO IMOVEL

NOME DE LOGRADOURO DO IMOVEL
AV  PAULISTA                         77929
AV  RAIMUNDO PEREIRA DE MAGALHAES    55815
R DA CONSOLACAO                      48862
AV BRIG LUIS ANTONIO                 46957
R  VERGUEIRO                         46871
AV  NOVE DE JULHO                    43988
AV BRIG FARIA LIMA                   43365
AV  CELSO GARCIA                     40689
R  BELA CINTRA                       37504
R  VOLUNTARIOS DA PATRIA             37337
AV  ANGELICA                         36800
AV  INTERLAGOS                       35613
R FREI CANECA                        33456
AL  SANTOS                           31434
AL  LORENA                           29945
AV DAS NACOES UNIDAS                 28548
AV PDE ARLINDO VIEIRA                28472
AV  VILA EMA                         27459
R  AUGUSTA                           26127
R  OSCAR FREIRE                      25828
Name: count, dtype: int64

Value counts for column: TIPO DE USO DO IMOVEL

TIPO DE USO DO IMOVEL
Apartamento em condomínio                                                                     8521073
Residência                                                                                    6491698
Residência coletiva, exclusive cortiço (mais de uma residência no lote)                       1225981
Garagem (unidade autônoma) em edifício em condomínio de uso exclusivamente residencial        1185071
Escritório/consultório em condomínio (unidade autônoma)                                        831480
Terreno                                                                                        628525
Residência e outro uso (predominância residencial)                                             512335
Loja                                                                                           324601
Loja e residência (predominância comercial)                                                    266636
Garagem (unidade autônoma) em edifício em condomínio de escritórios, consultórios ou misto     227966
Flat de uso comercial (semelhante a hotel)                                                     148873
Prédio de escritório ou consultório, não em condomínio, com ou sem lojas                       146405
Loja em edifício em condomínio (unidade autônoma)                                              141544
Outras edificações de uso comercial, com utilização múltipla                                   130481
Indústria                                                                                       79343
Oficina                                                                                         59395
Garagem (unidade autônoma) de prédio de garagens                                                56335
Armazéns gerais e depósitos                                                                     53737
Escola                                                                                          41769
Templo                                                                                          35933
Name: count, dtype: int64

Value counts for column: TIPO DE PADRAO DA CONSTRUCAO

TIPO DE PADRAO DA CONSTRUCAO
Residencial vertical - padrão C                                                     6382194
Residencial horizontal - padrão C                                                   3914083
Residencial horizontal - padrão B                                                   2366972
Residencial horizontal - padrão A                                                   1712458
Residencial vertical - padrão D                                                     1562978
Residencial vertical - padrão B                                                      977441
Comercial vertical - padrão C                                                        697734
TERRENO                                                                              628525
Comercial horizontal - padrão B                                                      546644
Residencial vertical - padrão A                                                      504219
Comercial vertical - padrão B                                                        343317
Residencial vertical - padrão E                                                      334241
Residencial horizontal - padrão D                                                    281627
Comercial vertical - padrão D                                                        248415
Comercial horizontal - padrão C                                                      127771
Comercial vertical - padrão E                                                        116219
Oficina/Posto de serviço/Armazém/Depósito/Indústria - padrão C                       115108
Barracão/Telheiro/Oficina/Posto de serviço/Armazém/Depósito/Indústria - padrão B      90836
Comercial horizontal - padrão A                                                       68680
Edifício de garagens - padrão A                                                       56546
Name: count, dtype: int64

In [ ]:
df_itbi = pd.read_csv('ITBI_2019_2024.csv')

display(df_itbi.head(20))
display(df_itbi.info())

/tmp/ipython-input-3293554480.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df_itbi = pd.read_csv('ITBI_2019_2024.csv')

,N° do Cadastro (SQL),Natureza de Transação,Valor de Transação (declarado pelo contribuinte),Data de Transação,Valor Venal de Referência,Proporção Transmitida (%),Valor Venal de Referência (proporcional),Base de Cálculo adotada,Tipo de Financiamento,Valor Financiado,Situação do SQL,Ano da Transacao,Mes da Transacao,Ano/Mes da Transacao
0,12310100659,1.Compra e venda,900000.00,2019-01-02,773836.00,100.00,773836.00,900000.00,1.Sistema Financeiro de Habitação,400000.00,Ativo Predial,2019,1,2019/01
1,5528502403,1.Compra e venda,420000.00,2019-01-02,303832.00,100.00,303832.00,420000.00,1.Sistema Financeiro de Habitação,340721.07,Ativo Predial,2019,1,2019/01
2,29903601032,1.Compra e venda,650000.00,2019-01-03,459364.00,100.00,459364.00,650000.00,NaN,0.00,Ativo Predial,2019,1,2019/01
3,4201104559,1.Compra e venda,61765.36,2019-01-03,300840.00,100.00,300840.00,300840.00,NaN,0.00,Ativo Predial,2019,1,2019/01
4,2206602970,1.Compra e venda,965000.00,2019-01-03,575501.00,100.00,575501.00,965000.00,NaN,0.00,Ativo Predial,2019,1,2019/01
5,4201104559,1.Compra e venda,62092.62,2019-01-03,300840.00,100.00,300840.00,300840.00,NaN,0.00,Ativo Predial,2019,1,2019/01
6,1500803995,1.Compra e venda,690000.00,2019-01-03,351710.00,100.00,351710.00,690000.00,NaN,0.00,Ativo Predial,2019,1,2019/01
7,23007502991,1.Compra e venda,175000.00,2019-01-02,47460.00,100.00,47460.00,175000.00,1.Sistema Financeiro de Habitação,138835.37,Ativo Predial,2019,1,2019/01
8,9016400885,1.Compra e venda,380000.00,2019-01-02,283295.00,100.00,283295.00,380000.00,NaN,0.00,Ativo Predial,2019,1,2019/01
9,9045201674,1.Compra e venda,440000.00,2019-01-03,453153.00,100.00,453153.00,453153.00,NaN,0.00,Ativo Predial,2019,1,2019/01
10,907109292,1.Compra e venda,1900000.00,2019-01-03,1084182.00,100.00,1084182.00,1900000.00,NaN,0.00,Ativo Predial,2019,1,2019/01
11,907110525,1.Compra e venda,145000.00,2019-01-03,93303.00,100.00,93303.00,145000.00,NaN,0.00,Ativo Predial,2019,1,2019/01
12,9016401520,1.Compra e venda,317000.00,2019-01-03,233334.00,100.00,233334.00,317000.00,NaN,0.00,Ativo Predial,2019,1,2019/01
13,17803800318,1.Compra e venda,10000.00,2019-01-03,295324.00,25.00,73831.00,73831.00,NaN,0.00,Ativo Predial,2019,1,2019/01
14,1001906462,1.Compra e venda,1350000.00,2019-01-04,1770203.00,100.00,1770203.00,1770203.00,NaN,0.00,Ativo Predial,2019,1,2019/01
15,1408801663,1.Compra e venda,865000.00,2019-01-02,632228.00,100.00,632228.00,865000.00,NaN,0.00,Ativo Predial,2019,1,2019/01
16,13503000134,1.Compra e venda,130000.00,2019-01-04,395043.00,50.00,197521.50,197521.50,NaN,0.00,Ativo Predial,2019,1,2019/01
17,14203201550,1.Compra e venda,22000.00,2019-01-03,107484.00,21.34,22937.09,22937.09,NaN,0.00,Ativo Predial,2019,1,2019/01
18,13503000134,1.Compra e venda,130000.00,2019-01-04,395043.00,50.00,197521.50,197521.50,NaN,0.00,Ativo Predial,2019,1,2019/01
19,11503801186,1.Compra e venda,180000.00,2019-01-03,78857.00,100.00,78857.00,180000.00,1.Sistema Financeiro de Habitação,144000.00,Ativo Predial,2019,1,2019/01

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 941624 entries, 0 to 941623
Data columns (total 14 columns):
 #   Column                                            Non-Null Count   Dtype
---  ------                                            --------------   -----
 0   N° do Cadastro (SQL)                              941624 non-null  object
 1   Natureza de Transação                             941624 non-null  object
 2   Valor de Transação (declarado pelo contribuinte)  941624 non-null  float64
 3   Data de Transação                                 941624 non-null  object
 4   Valor Venal de Referência                         941624 non-null  float64
 5   Proporção Transmitida (%)                         941624 non-null  float64
 6   Valor Venal de Referência (proporcional)          941624 non-null  float64
 7   Base de Cálculo adotada                           941452 non-null  float64
 8   Tipo de Financiamento                             366002 non-null  object
 9   Valor Financiado                                  941624 non-null  float64
 10  Situação do SQL                                   941624 non-null  object
 11  Ano da Transacao                                  941624 non-null  int64
 12  Mes da Transacao                                  941624 non-null  int64
 13  Ano/Mes da Transacao                              941624 non-null  object
dtypes: float64(6), int64(2), object(6)
memory usage: 100.6+ MB

None

In [ ]:
missing_values = df_itbi.isnull().sum()
display(missing_values)

N° do Cadastro (SQL)                                     0
Natureza de Transação                                    0
Valor de Transação (declarado pelo contribuinte)         0
Data de Transação                                        0
Valor Venal de Referência                                0
Proporção Transmitida (%)                                0
Valor Venal de Referência (proporcional)                 0
Base de Cálculo adotada                                172
Tipo de Financiamento                               575622
Valor Financiado                                         0
Situação do SQL                                          0
Ano da Transacao                                         0
Mes da Transacao                                         0
Ano/Mes da Transacao                                     0
dtype: int64

In [ ]:
numerical_columns = df_itbi.select_dtypes(include=['int64', 'float64'])
descriptive_stats = numerical_columns.describe()
display(descriptive_stats)

,Valor de Transação (declarado pelo contribuinte),Valor Venal de Referência,Proporção Transmitida (%),Valor Venal de Referência (proporcional),Base de Cálculo adotada,Valor Financiado,Ano da Transacao,Mes da Transacao
count,941624.00,941624.00,941624.00,941624.00,941452.00,941624.00,941624.00,941624.00
mean,626009.55,4529642.36,68.50,412186.87,673961.17,105033.28,2021.88,6.91
std,2860634.38,20294328.56,44.73,2149073.29,2964741.19,187384.37,1.66,3.36
min,0.00,0.00,0.00,0.00,0.00,-604339.00,2019.00,1.00
25%,215000.00,231835.50,1.06,37039.02,230000.00,0.00,2021.00,4.00
50%,307600.00,452579.00,100.00,206322.00,330000.00,0.00,2022.00,7.00
75%,550000.00,1716756.75,100.00,416320.00,600000.00,189000.00,2023.00,10.00
max,729435080.10,1652865322.00,823.64,488407868.00,729435080.10,29000000.00,2024.00,12.00

In [ ]:
categorical_columns = df_itbi.select_dtypes(include='object').columns.tolist()
display(categorical_columns)
categorical_columns.remove('N° do Cadastro (SQL)')

for col in categorical_columns:
    print(f"\nValue counts for column: {col}")
    if df_itbi[col].nunique() > 20:
        display(df_itbi[col].value_counts().head(20))
    else:
        display(df_itbi[col].value_counts())

['N° do Cadastro (SQL)',
 'Natureza de Transação',
 'Data de Transação',
 'Tipo de Financiamento',
 'Situação do SQL',
 'Ano/Mes da Transacao']

Value counts for column: Natureza de Transação

Natureza de Transação
1.Compra e venda                                                          850480
12.Dação em pagamento por escritura pública                                21319
20.Realização ou integralização de capital                                 12025
2.Cessão de direitos relativos a compromisso de compra e venda              9211
15.Permuta por escritura pública                                            8751
4.Arrematação (em leilão ou hasta pública)                                  8396
17.Resolução da alienação fiduciária por inadimplemento                     7814
33.Demais atos onerosos translativos                                        6140
3.Adjudicação (vinculada a processo de execução ou cobrança de dívida)      3279
26.Cessão de direitos sobre o imóvel com alienação fiduciária               2696
8.Cessão de direitos hereditários (ou sucessórios)                          1958
5.Adjudicação compulsória                                                   1808
29.Excesso de meação na partilha (separação / divórcio)                     1149
27.Excesso de quinhão ou quota-parte na divisão amigável ou judicial        1141
34.Demais sentenças judiciais                                               1084
5.Excesso de meação ou quinhão na partilha                                   905
23.Cisão total ou parcial                                                    895
24.Extinção de pessoa jurídica                                               697
40.Excesso na integralização de capital                                      547
28.Excesso de meação ou quinhão na partilha (sucessão causa mortis)          275
Name: count, dtype: int64

Value counts for column: Data de Transação

Data de Transação
2024-08-30    2212
2024-11-29    2172
2024-03-28    2012
2023-06-30    1988
2023-09-29    1883
2024-06-28    1820
2022-09-30    1735
2024-09-30    1702
2024-04-30    1693
2024-06-21    1615
2024-10-31    1609
2022-06-30    1568
2019-12-20    1527
2020-12-18    1525
2024-04-10    1517
2023-11-30    1507
2024-07-31    1496
2023-12-22    1467
2024-04-22    1426
2023-04-28    1423
Name: count, dtype: int64

Value counts for column: Tipo de Financiamento

Tipo de Financiamento
1.Sistema Financeiro de Habitação    315364
2.Minha Casa Minha Vida               44723
3.Consórcio                            4698
99.SFI, Carteira Hipotecária, etc      1206
5.                                        8
4.                                        3
Name: count, dtype: int64

Value counts for column: Situação do SQL

Situação do SQL
Ativo Predial            794796
Ativo Territorial        108525
Cancelado Predial         18714
Cancelado Territorial     14921
Não_Existe_Exercício       4668
Name: count, dtype: int64

Value counts for column: Ano/Mes da Transacao

Ano/Mes da Transacao
2024/08    20427
2024/10    20354
2024/04    20235
2024/07    19472
2024/09    18820
2024/06    18620
2024/05    18392
2024/11    18223
2024/03    17026
2023/08    16940
2021/12    16893
2023/12    16433
2024/12    16243
2023/05    16164
2021/08    16131
2023/03    16064
2021/11    15858
2023/06    15798
2023/09    15424
2023/10    15276
Name: count, dtype: int64